# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jerryweijin.github.io',
                'doc_host': 'https://jerryweijin.github.io',
                'git_url': 'https://github.com/jerryweijin/jerryweijin.github.io',
                'lib_path': 'jerryweijin.github.io'},
  'syms': {'jerryweijin.github.io.core': {'jerryweijin.github.io.core.foo': ('core.html#foo', 'jerryweijin.github.io/core.py')}}}
